name = "blogapp"
compatibility_date = "2024-04-01"
pages_build_output_dir = ".vercel/output/static"

[site]
bucket = ".vercel/output/static"

[vars]
# Supabase & Gemini keys are already inlined or in dashboard

[[routes]]
pattern = "blogapp.reqbox12.workers.dev/*"
script = "_worker.js"

[observability]
enabled = true
